const CHARACTERS = [
  {
    id:"aemeath",
    name:"Aemeath",
    rarity:"5★",
    image:"assets/wuwa/icons/aemeath.jpg",
    icons:[
      "assets/wuwa/resonance/aemeath/1.jpg",
      "assets/wuwa/resonance/aemeath/2.jpg",
      "assets/wuwa/resonance/aemeath/3.jpg",
      "assets/wuwa/resonance/aemeath/4.jpg",
      "assets/wuwa/resonance/aemeath/5.jpg",
      "assets/wuwa/resonance/aemeath/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/sword.jpg",
      "assets/wuwa/weapon/aemeath.jpg"
    ]
  },
  {
    id:"augusta",
    name:"Augusta",
    rarity:"5★",
    image:"assets/wuwa/icons/augusta.jpg",
    icons:[
      "assets/wuwa/resonance/augusta/1.jpg",
      "assets/wuwa/resonance/augusta/2.jpg",
      "assets/wuwa/resonance/augusta/3.jpg",
      "assets/wuwa/resonance/augusta/4.jpg",
      "assets/wuwa/resonance/augusta/5.jpg",
      "assets/wuwa/resonance/augusta/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/broadblade.jpg",
      "assets/wuwa/weapon/augusta.jpg"
    ]
  },
  {
    id:"brant",
    name:"Brant",
    rarity:"5★",
    image:"assets/wuwa/icons/brant.jpg",
    icons:[
      "assets/wuwa/resonance/brant/1.jpg",
      "assets/wuwa/resonance/brant/2.jpg",
      "assets/wuwa/resonance/brant/3.jpg",
      "assets/wuwa/resonance/brant/4.jpg",
      "assets/wuwa/resonance/brant/5.jpg",
      "assets/wuwa/resonance/brant/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/sword.jpg",
      "assets/wuwa/weapon/brant.jpg"
    ]
  },
  {
    id:"camellya",
    name:"Camellya",
    rarity:"5★",
    image:"assets/wuwa/icons/camellya.jpg",
    icons:[
      "assets/wuwa/resonance/camellya/1.jpg",
      "assets/wuwa/resonance/camellya/2.jpg",
      "assets/wuwa/resonance/camellya/3.jpg",
      "assets/wuwa/resonance/camellya/4.jpg",
      "assets/wuwa/resonance/camellya/5.jpg",
      "assets/wuwa/resonance/camellya/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/sword.jpg",
      "assets/wuwa/weapon/camellya.jpg"
    ]
  },
  {
    id:"cantarella",
    name:"Cantarella",
    rarity:"5★",
    image:"assets/wuwa/icons/cantarella.jpg",
    icons:[
      "assets/wuwa/resonance/cantarella/1.jpg",
      "assets/wuwa/resonance/cantarella/2.jpg",
      "assets/wuwa/resonance/cantarella/3.jpg",
      "assets/wuwa/resonance/cantarella/4.jpg",
      "assets/wuwa/resonance/cantarella/5.jpg",
      "assets/wuwa/resonance/cantarella/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/rectifier.jpg",
      "assets/wuwa/weapon/cantarella.jpg"
    ]
  },
  {
    id:"carlotta",
    name:"Carlotta",
    rarity:"5★",
    image:"assets/wuwa/icons/carlotta.jpg",
    icons:[
      "assets/wuwa/resonance/carlotta/1.jpg",
      "assets/wuwa/resonance/carlotta/2.jpg",
      "assets/wuwa/resonance/carlotta/3.jpg",
      "assets/wuwa/resonance/carlotta/4.jpg",
      "assets/wuwa/resonance/carlotta/5.jpg",
      "assets/wuwa/resonance/carlotta/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/pistol.jpg",
      "assets/wuwa/weapon/carlotta.jpg"
    ]
  },
  {
    id:"cartethyia",
    name:"Cartethyia",
    rarity:"5★",
    image:"assets/wuwa/icons/cartethyia.jpg",
    icons:[
      "assets/wuwa/resonance/cartethyia/1.jpg",
      "assets/wuwa/resonance/cartethyia/2.jpg",
      "assets/wuwa/resonance/cartethyia/3.jpg",
      "assets/wuwa/resonance/cartethyia/4.jpg",
      "assets/wuwa/resonance/cartethyia/5.jpg",
      "assets/wuwa/resonance/cartethyia/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/sword.jpg",
      "assets/wuwa/weapon/cartethyia.jpg"
    ]
  },
  {
    id:"changli",
    name:"Changli",
    rarity:"5★",
    image:"assets/wuwa/icons/changli.jpg",
    icons:[
      "assets/wuwa/resonance/changli/1.jpg",
      "assets/wuwa/resonance/changli/2.jpg",
      "assets/wuwa/resonance/changli/3.jpg",
      "assets/wuwa/resonance/changli/4.jpg",
      "assets/wuwa/resonance/changli/5.jpg",
      "assets/wuwa/resonance/changli/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/sword.jpg",
      "assets/wuwa/weapon/changli.jpg"
    ]
  },
  {
    id:"chisa",
    name:"Chisa",
    rarity:"5★",
    image:"assets/wuwa/icons/chisa.jpg",
    icons:[
      "assets/wuwa/resonance/chisa/1.jpg",
      "assets/wuwa/resonance/chisa/2.jpg",
      "assets/wuwa/resonance/chisa/3.jpg",
      "assets/wuwa/resonance/chisa/4.jpg",
      "assets/wuwa/resonance/chisa/5.jpg",
      "assets/wuwa/resonance/chisa/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/broadblade.jpg",
      "assets/wuwa/weapon/chisa.jpg"
    ]
  },
  {
    id:"ciaccona",
    name:"Ciaccona",
    rarity:"5★",
    image:"assets/wuwa/icons/ciaccona.jpg",
    icons:[
      "assets/wuwa/resonance/ciaccona/1.jpg",
      "assets/wuwa/resonance/ciaccona/2.jpg",
      "assets/wuwa/resonance/ciaccona/3.jpg",
      "assets/wuwa/resonance/ciaccona/4.jpg",
      "assets/wuwa/resonance/ciaccona/5.jpg",
      "assets/wuwa/resonance/ciaccona/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/pistol.jpg",
      "assets/wuwa/weapon/ciaccona.jpg"
    ]
  },
  {
    id:"galbrena",
    name:"Galbrena",
    rarity:"5★",
    image:"assets/wuwa/icons/galbrena.jpg",
    icons:[
      "assets/wuwa/resonance/galbrena/1.jpg",
      "assets/wuwa/resonance/galbrena/2.jpg",
      "assets/wuwa/resonance/galbrena/3.jpg",
      "assets/wuwa/resonance/galbrena/4.jpg",
      "assets/wuwa/resonance/galbrena/5.jpg",
      "assets/wuwa/resonance/galbrena/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/pistol.jpg",
      "assets/wuwa/weapon/galbrena.jpg"
    ]
  },
  {
    id:"iuno",
    name:"Iuno",
    rarity:"5★",
    image:"assets/wuwa/icons/iuno.jpg",
    icons:[
      "assets/wuwa/resonance/iuno/1.jpg",
      "assets/wuwa/resonance/iuno/2.jpg",
      "assets/wuwa/resonance/iuno/3.jpg",
      "assets/wuwa/resonance/iuno/4.jpg",
      "assets/wuwa/resonance/iuno/5.jpg",
      "assets/wuwa/resonance/iuno/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/gauntlet.jpg",
      "assets/wuwa/weapon/iuno.jpg"
    ]
  },
  {
    id:"jinhsi",
    name:"Jinhsi",
    rarity:"5★",
    image:"assets/wuwa/icons/jinhsi.jpg",
    icons:[
      "assets/wuwa/resonance/jinhsi/1.jpg",
      "assets/wuwa/resonance/jinhsi/2.jpg",
      "assets/wuwa/resonance/jinhsi/3.jpg",
      "assets/wuwa/resonance/jinhsi/4.jpg",
      "assets/wuwa/resonance/jinhsi/5.jpg",
      "assets/wuwa/resonance/jinhsi/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/broadblade.jpg",
      "assets/wuwa/weapon/jinhsi.jpg"
    ]
  },
  {
    id:"jiyan",
    name:"Jiyan",
    rarity:"5★",
    image:"assets/wuwa/icons/jiyan.jpg",
    icons:[
      "assets/wuwa/resonance/jiyan/1.jpg",
      "assets/wuwa/resonance/jiyan/2.jpg",
      "assets/wuwa/resonance/jiyan/3.jpg",
      "assets/wuwa/resonance/jiyan/4.jpg",
      "assets/wuwa/resonance/jiyan/5.jpg",
      "assets/wuwa/resonance/jiyan/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/broadblade.jpg",
      "assets/wuwa/weapon/jiyan.jpg"
    ]
  },
  {
    id:"lupa",
    name:"Lupa",
    rarity:"5★",
    image:"assets/wuwa/icons/lupa.jpg",
    icons:[
      "assets/wuwa/resonance/lupa/1.jpg",
      "assets/wuwa/resonance/lupa/2.jpg",
      "assets/wuwa/resonance/lupa/3.jpg",
      "assets/wuwa/resonance/lupa/4.jpg",
      "assets/wuwa/resonance/lupa/5.jpg",
      "assets/wuwa/resonance/lupa/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/broadblade.jpg",
      "assets/wuwa/weapon/lupa.jpg"
    ]
  },
  {
    id:"luuk herssen",
    name:"Luuk Hessen",
    rarity:"5★",
    image:"assets/wuwa/icons/luuk-herssen.jpg",
    icons:[
      "assets/wuwa/resonance/luuk-herssen/1.jpg",
      "assets/wuwa/resonance/luuk-herssen/2.jpg",
      "assets/wuwa/resonance/luuk-herssen/3.jpg",
      "assets/wuwa/resonance/luuk-herssen/4.jpg",
      "assets/wuwa/resonance/luuk-herssen/5.jpg",
      "assets/wuwa/resonance/luuk-herssen/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapons/mornye_1.jpg",
      "assets/wuwa/weapon/mornye_2.jpg"
    ]
  },
  {
    id:"lynae",
    name:"Lynae",
    rarity:"5★",
    image:"assets/wuwa/icons/lynae.jpg",
    icons:[
      "assets/wuwa/resonance/lynae/1.jpg",
      "assets/wuwa/resonance/lynae/2.jpg",
      "assets/wuwa/resonance/lynae/3.jpg",
      "assets/wuwa/resonance/lynae/4.jpg",
      "assets/wuwa/resonance/lynae/5.jpg",
      "assets/wuwa/resonance/lynae/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/pistol.jpg",
      "assets/wuwa/weapon/lynae.jpg"
    ]
  },
  {
    id:"mornye",
    name:"Mornye",
    rarity:"5★",
    image:"assets/wuwa/icons/mornye.jpg",
    icons:[
      "assets/wuwa/resonance/mornye/1.jpg",
      "assets/wuwa/resonance/mornye/2.jpg",
      "assets/wuwa/resonance/mornye/3.jpg",
      "assets/wuwa/resonance/mornye/4.jpg",
      "assets/wuwa/resonance/mornye/5.jpg",
      "assets/wuwa/resonance/mornye/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/broadblade.jpg",
      "assets/wuwa/weapon/mornye.jpg"
    ]
  },
  {
    id:"phoebe",
    name:"Phoebe",
    rarity:"5★",
    image:"assets/wuwa/icons/phoebe.jpg",
    icons:[
      "assets/wuwa/resonance/phoebe/1.jpg",
      "assets/wuwa/resonance/phoebe/2.jpg",
      "assets/wuwa/resonance/phoebe/3.jpg",
      "assets/wuwa/resonance/phoebe/4.jpg",
      "assets/wuwa/resonance/phoebe/5.jpg",
      "assets/wuwa/resonance/phoebe/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/rectifier.jpg",
      "assets/wuwa/weapon/phoebe.jpg"
    ]
  },
  {
    id:"phrolova",
    name:"Phrolova",
    rarity:"5★",
    image:"assets/wuwa/icons/phrolova.jpg",
    icons:[
      "assets/wuwa/resonance/phrolova/1.jpg",
      "assets/wuwa/resonance/phrolova/2.jpg",
      "assets/wuwa/resonance/phrolova/3.jpg",
      "assets/wuwa/resonance/phrolova/4.jpg",
      "assets/wuwa/resonance/phrolova/5.jpg",
      "assets/wuwa/resonance/phrolova/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/rectifier.jpg",
      "assets/wuwa/weapon/phrolova.jpg"
    ]
  },
  {
    id:"qiuyuan",
    name:"Qiuyuan",
    rarity:"5★",
    image:"assets/wuwa/icons/qiuyuan.jpg",
    icons:[
      "assets/wuwa/resonance/qiuyuan/1.jpg",
      "assets/wuwa/resonance/qiuyuan/2.jpg",
      "assets/wuwa/resonance/qiuyuan/3.jpg",
      "assets/wuwa/resonance/qiuyuan/4.jpg",
      "assets/wuwa/resonance/qiuyuan/5.jpg",
      "assets/wuwa/resonance/qiuyuan/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/sword.jpg",
      "assets/wuwa/weapon/qiuyuan.jpg"
    ]
  },
  {
    id:"roccia",
    name:"Roccia",
    rarity:"5★",
    image:"assets/wuwa/icons/roccia.jpg",
    icons:[
      "assets/wuwa/resonance/roccia/1.jpg",
      "assets/wuwa/resonance/roccia/2.jpg",
      "assets/wuwa/resonance/roccia/3.jpg",
      "assets/wuwa/resonance/roccia/4.jpg",
      "assets/wuwa/resonance/roccia/5.jpg",
      "assets/wuwa/resonance/roccia/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/gauntlet.jpg",
      "assets/wuwa/weapon/roccia.jpg"
    ]
  },
  {
    id:"shorekeeper",
    name:"Shorekeeper",
    rarity:"5★",
    image:"assets/wuwa/icons/shorekeeper.jpg",
    icons:[
      "assets/wuwa/resonance/shorekeeper/1.jpg",
      "assets/wuwa/resonance/shorekeeper/2.jpg",
      "assets/wuwa/resonance/shorekeeper/3.jpg",
      "assets/wuwa/resonance/shorekeeper/4.jpg",
      "assets/wuwa/resonance/shorekeeper/5.jpg",
      "assets/wuwa/resonance/shorekeeper/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/rectifier.jpg",
      "assets/wuwa/weapon/shorekeeper.jpg"
    ]
  },
  {
    id:"xiangli yao",
    name:"Xiangli Yao",
    rarity:"5★",
    image:"assets/wuwa/icons/xiangli-yao.jpg",
    icons:[
      "assets/wuwa/resonance/xiangli-yao/1.jpg",
      "assets/wuwa/resonance/xiangli-yao/2.jpg",
      "assets/wuwa/resonance/xiangli-yao/3.jpg",
      "assets/wuwa/resonance/xiangli-yao/4.jpg",
      "assets/wuwa/resonance/xiangli-yao/5.jpg",
      "assets/wuwa/resonance/xiangli-yao/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/gauntlet.jpg",
      "assets/wuwa/weapon/xiangli-yao.jpg"
    ]
  },
  {
    id:"yinlin",
    name:"Yinlin",
    rarity:"5★",
    image:"assets/wuwa/icons/yinlin.jpg",
    icons:[
      "assets/wuwa/resonance/yinlin/1.jpg",
      "assets/wuwa/resonance/yinlin/2.jpg",
      "assets/wuwa/resonance/yinlin/3.jpg",
      "assets/wuwa/resonance/yinlin/4.jpg",
      "assets/wuwa/resonance/yinlin/5.jpg",
      "assets/wuwa/resonance/yinlin/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/rectifier.jpg",
      "assets/wuwa/weapon/yinlin.jpg"
    ]
  },
  {
    id:"zani",
    name:"Zani",
    rarity:"5★",
    image:"assets/wuwa/icons/zani.jpg",
    icons:[
      "assets/wuwa/resonance/zani/1.jpg",
      "assets/wuwa/resonance/zani/2.jpg",
      "assets/wuwa/resonance/zani/3.jpg",
      "assets/wuwa/resonance/zani/4.jpg",
      "assets/wuwa/resonance/zani/5.jpg",
      "assets/wuwa/resonance/zani/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/gauntlet.jpg",
      "assets/wuwa/weapon/zani.jpg"
    ]
  },
  {
    id:"zhezhi",
    name:"Zhezhi",
    rarity:"5★",
    image:"assets/wuwa/icons/zhezhi.jpg",
    icons:[
      "assets/wuwa/resonance/zhezhi/1.jpg",
      "assets/wuwa/resonance/zhezhi/2.jpg",
      "assets/wuwa/resonance/zhezhi/3.jpg",
      "assets/wuwa/resonance/zhezhi/4.jpg",
      "assets/wuwa/resonance/zhezhi/5.jpg",
      "assets/wuwa/resonance/zhezhi/6.jpg"
    ],
    weapons:[
      "assets/wuwa/weapon/icons/rectifier.jpg",
      "assets/wuwa/weapon/zhezhi.jpg"
    ]
  },
];
